### ISSUE TITLE
Move this crate under wasmCloud repository

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/provider-archive#14]
`provider-archive` is primarily used by wasmCloud, and in the interest of consolidating our crates and repositories, it should be relocated to the crates/ subdirectory of the wasmCloud repo.

This can be done in such a way that preserves individual git histories, and we should do that to preserve commits, releases, and contributors.

**Comment by autodidaddict** [comment]
Bumping this so we don't forget about it...

**Comment by brooksmtownsend** [comment]
I'm failing to find the issue right now for some reason, but we do have an issue for testing out [bindle](https://github.com/deislabs/bindle) right? I think we should do that before we go through the process of merging commit histories, releases, actions, etc 🙂

**Comment by brooksmtownsend** [comment]
Issue for testing bindle: https://github.com/wasmCloud/capability-providers/issues/17
